Altador:
  Altador Map: http://www.neopets.com/altador/index.phtml
  Altador Cup: http://www.neopets.com/altador/colosseum/

Brightvale:
  Brightvale Map: http://www.neopets.com/medieval/brightvale.phtml
  Brightvale Armoury: http://www.neopets.com/objects.phtml?type=shop&obj_type=80

Faerieland:
  Faerieland Map: http://www.neopets.com/faerieland/index.phtml
  Faerie Bubbles: http://www.neopets.com/games/play.phtml?game_id=358
  TDMBGPOP: http://www.neopets.com/faerieland/tdmbgpop.phtml

Moltara:
  Lampwyck's Lights Fantastic: http://www.neopets.com/objects.phtml?type=shop&obj_type=110
