Altador:
  Altador Map: http://www.neopets.com/altador/index.phtml
  Altador Cup: http://www.neopets.com/altador/colosseum/
  Altadorian Archives: http://www.neopets.com/altador/archives.phtml
  Altadorian Archivist: http://www.neopets.com/altador/archives.phtml?archivist=1
  Clouds: http://www.neopets.com/altador/clouds.phtml
  Club, Alchemy: http://www.neopets.com/altador/archives.phtml?board=5
  Club, Astronomy: http://www.neopets.com/altador/archives.phtml?board=6
  Club, Engineering: http://www.neopets.com/altador/archives.phtml?board=6
  Club, Herbalism: http://www.neopets.com/altador/archives.phtml?board=1
  Club, Mining: http://www.neopets.com/altador/archives.phtml?board=2
  Council: http://www.neopets.com/altador/council.phtml
  Docks: http://www.neopets.com/altador/docks.phtml
  Exquisite Ambrosia: http://www.neopets.com/objects.phtml?type=shop&obj_type=95
  Hall of Heroes: http://www.neopets.com/altador/hallofheroes.phtml
  Illustrious Armoury: http://www.neopets.com/objects.phtml?type=shop&obj_type=94
  Legendary Petpets: http://www.neopets.com/objects.phtml?type=shop&obj_type=97
  Magical Marvels: http://www.neopets.com/objects.phtml?type=shop&obj_type=96
  Observatory: http://www.neopets.com/altador/hallofheroes.phtml?stairs=1
  Perfectly Flat Rock Quarry: http://www.neopets.com/altador/quarry.phtml
  Statue 1, Jerdana: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=1
  Statue 2, Siyana: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=2
  Statue 3, Kelland: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=3
  Statue 4, Florin: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=4
  Statue 5, Torakor: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=5
  Statue 6, Darkest Faerie: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=6
  Statue 7, Marak: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=7
  Statue 8, Fauna: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=8
  Statue 9, Psellia: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=9
  Statue 10, Gordos: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=10
  Statue 11, Sasha: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=11
  Statue 12, King Altador: http://www.neopets.com/altador/hallofheroes.phtml?view_statue_id=12
  The Old Follies Farm: http://www.neopets.com/altador/farm.phtml
  Tomb: http://www.neopets.com/altador/tomb.phtml
  Water Distribution Plant: http://www.neopets.com/altador/plant.phtml

Brightvale:
  Brightvale Map: http://www.neopets.com/medieval/brightvale.phtml
  Brightvale Armoury: http://www.neopets.com/objects.phtml?type=shop&obj_type=80

Faerieland:
  Faerieland Map: http://www.neopets.com/faerieland/index.phtml
  Faerie Bubbles: http://www.neopets.com/games/play.phtml?game_id=358
  TDMBGPOP: http://www.neopets.com/faerieland/tdmbgpop.phtml

Moltara:
  Lampwyck's Lights Fantastic: http://www.neopets.com/objects.phtml?type=shop&obj_type=110
